required-players: 2
countdown-seconds: 15
lobby-spawn:
    world: "world"
    x: 0
    y: 101
    z: 0
    yaw: -180
    pitch: 0
arenas:
  0:
    world: "world"
    y-respawn: 80
    spawns:
      green:
        x: -10.5
        y: 93
        z: 5.5
        yaw: 0
        pitch: 0
      blue:
        x: -10.5
        y: 93
        z: -4.5
        yaw: 0
        pitch: 0
      yellow:
        x: 2.5
        y: 93
        z: -4.5
        yaw: 0
        pitch: 0
      red:
        x: 2.5
        y: 93
        z: 5.5
        yaw: 0
        pitch: 0
    beds:
      green:
        x: -10.5
        y: 92
        z: 5.5
        facing: east
      blue:
        x: -10.5
        y: 92
        z: -4.5
        facing: east
      yellow:
        x: 1.5
        y: 92
        z: -4.5
        facing: west
      red:
        x: 1.5
        y: 92
        z: 5.5
        facing: west